server:
  port: 8081
spring:
  application:
    name: article-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microserviceDb
    username: root
    password: Ohr500082TS
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
application:
  config:
    author-url: http://localhost:8000/api/v1/author
