server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: article-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/articles/**
          - id: author-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/author/**